openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /device:
    get:
      summary: Returns a list of device.
      responses:
        '200':
          description: A JSON array of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
