openapi: 3.1.0
info:
  title: EletroAPI
  description: ''
  contact: {}
  version: '1.0'
servers:
- url: http://127.0.0.1:8000/api
  variables: {}
paths:
  /device:
    put:
      tags:
      - Device
      summary: Device Update
      description: ''
      operationId: DeviceUpdate
      parameters:
      - name: id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          contentEncoding: int32
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - brand
              - name
              - description
              - voltage
              type: object
              properties:
                brand:
                  type: string
                name:
                  type: string
                description:
                  type: string
                voltage:
                  type: string
              contentMediaType: application/x-www-form-urlencoded
        required: false
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                contentMediaType: text/plain
      deprecated: false
    get:
      tags:
      - Device
      summary: Device List
      description: ''
      operationId: DeviceList
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                contentMediaType: text/plain
      deprecated: false
      security: []
    delete:
      tags:
      - Device
      summary: Device Delete
      description: ''
      operationId: DeviceDelete
      parameters:
      - name: id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          contentEncoding: int32
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                contentMediaType: text/plain
      deprecated: false
    post:
      tags:
      - Device
      summary: Device Create
      description: ''
      operationId: DeviceCreate
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - brand
              - name
              - description
              - voltage
              type: object
              properties:
                brand:
                  type: string
                name:
                  type: string
                  examples:
                  - testename
                description:
                  type: string
                  examples:
                  - teste descr
                voltage:
                  type: string
                  examples:
                  - '230'
              contentMediaType: application/x-www-form-urlencoded
        required: false
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                contentMediaType: text/plain
      deprecated: false
    parameters: []
components:
  schemas: {}
